
= Tests

CANDLE tests

These should be runnable interactively or via Jenkins.

== Info

The Jenkins project is here:
https://jenkins-ci.cels.anl.gov/job/CANDLE-CR

== Usage

First, make sure your desired Python installation is in PATH and PYTHONPATH as needed.

Second, simply run the test you want, e.g.:

----
$ nice ./cr-nt3-1.sh
----

== Conventions

Each test has a separate run directory (RUNDIR), but this is overwritten from run to run.  We assume the numbered/dated output logs in Jenkins will capture everything needed to debug a test run.

== Utilities

check-count.sh::
Output checker

check-output.sh::
Output checker

check_tf.py::
Keras/TensorFlow settings reporter

checkout-benchmarks.sh::
Checks out or updates Benchmarks into a subdirectory

py-settings.sh::
Report Python settings

utils.sh::
Shell scripting tools

== Test list

cr-nt3-1.sh::
Test checkpoint/restart for NT3

cr-p1b1-torch-1.sh::
Test checkpoint/restart for P1B1/PyTorch

== Adding a new test

. Duplicate cr-nt3-1.sh
. Change the commands in the subshell to do what you want
. Check the output with the check-*.sh scripts or add your own tests
